apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
  labels: 
    app: myweb-app
spec:
  replicas: 1
  selector:
    matchLabels:
       env: production
  template:
    metadata:
     name: myweb-pod
     labels:
       env: production
    spec:
      containers:
      - name: myweb-con
        image: shubham532/task:1
        ports:
        - containerPort: 80
